### ISSUE TITLE
phpMemcacheAdmin don't show stats of instances running binary protocol (SASL enabled)

### ISSUE THREAD

**Issue by ranmses** [wp-cloud/phpmemcacheadmin#40]
Hello!

Versions:
- CentOS 6.6
- Compiled memcached-1.4.21-1.el6.x86_64
- phpMemcachedAdmin-1.3.0

Problem: with "-S" I cannot see stats.

I wonder if phpMemcachedAdmin isn't capable of reading data "binary protocol" instances. If that's the case, is it possible to add this functionality?

I actually submitted some time ago but no answer received: https://code.google.com/p/phpmemcacheadmin/issues/detail?id=28

Thank you!

**Comment by cfoellmann** [comment]
Why did you close this?
Did you fix it?
